### ISSUE TITLE
Error parsing config file

### ISSUE THREAD

**Issue by doubledave** [tayjaybabee/itsm#2] opened 2019-12-24 15:42 UTC
console log:

itsm$ python scripts/py/Forecast.py 
2019-12-24 08:10:45,380::ITSMApp.IPtoGP::INFO      Logger started for ITSMApp.IPtoGP
2019-12-24 08:10:45,381::ITSMApp.Forecast-Weather::INFO      Logger started for ITSMApp.Forecast-Weather
/home/david/src/itsm/scripts/py/forecast/media/icons/weather_conditions/static
2019-12-24 08:10:45,381::ITSMApp.Forecast::INFO      Logger started for ITSMApp.Forecast
2019-12-24 08:10:45,381::ITSMApp.Forecast::INFO      The logger is awake
2019-12-24 08:10:45,418::ITSMApp.ITSMConfig::INFO      Logger started for ITSMApp.ITSMConfig
2019-12-24 08:10:45,419::ITSMApp.Forecast::DEBUG     Determining where in the filesystem I am
2019-12-24 08:10:45,419::ITSMApp.Forecast::DEBUG      Found path: /home/david/src/itsm/scripts/py
2019-12-24 08:10:45,419::ITSMApp.ITSMConfig::DEBUG     Found /home/david/src/itsm/scripts/py/forecast/conf/example_forecast_conf.json
Traceback (most recent call last):
  File "scripts/py/Forecast.py", line 38, in <module>
    settings = config.readConf(confFile)['applets']['forecast']['settings']
  File "/home/david/src/itsm/scripts/py/application/itsmConfig.py", line 18, in readConf
    info = commentjson.loads(confInfo.read())
  File "/home/david/src/itsm/venv/lib/python3.7/site-packages/commentjson/commentjson.py", line 168, in loads
    parsed = parser.parse(text)
  File "/home/david/src/itsm/venv/lib/python3.7/site-packages/lark/lark.py", line 311, in parse
    return self.parser.parse(text, start=start)
  File "/home/david/src/itsm/venv/lib/python3.7/site-packages/lark/parser_frontends.py", line 185, in parse
    return self._parse(text, start)
  File "/home/david/src/itsm/venv/lib/python3.7/site-packages/lark/parser_frontends.py", line 54, in _parse
    return self.parser.parse(input, start, *args)
  File "/home/david/src/itsm/venv/lib/python3.7/site-packages/lark/parsers/earley.py", line 310, in parse
    raise UnexpectedEOF(expected_tokens)
lark.exceptions.UnexpectedEOF: Unexpected end-of-input. Expected one of: 
        * COMMA
        * RBRACE

**Comment by tayjaybabee** [comment] 2019-12-24 15:48
This error is caused by the example_forecast_conf.json file missing a final closing bracket(or right-brace: '}' ).

**Comment by tayjaybabee** [comment] 2019-12-24 16:07
Fixed in 867676008d7bbb79dcd74afd1df3c5cdc970a726

**Closed as completed by tayjaybabee** 2019-12-24 16:07 UTC
Labels: bug, good first issue, on master branch, confirmed
